### ISSUE TITLE
In the cli hide time and other metadata behind a parameter

### ISSUE THREAD

**Issue by kstaken** [terascope/ts-transforms#1]
The execution time is a good thing to be able to see but in it's default mode the command should just output the results with out any other text so that the output is easily piped to other commands.

**Comment by kstaken** [comment]
There's still a `results:` in the output

**Comment by jsnoble** [comment]
the `results:` is piped to stderr while the results are piped to stdout. Regular piping will only get the data without any extra stuff. Here is an example to verify
`./bin/ts-transform.js -r ./some/rules.txt -d ./some/data.txt | tee ./some/destination.txt`
